import type { NextPage } from "next";
import Head from "next/head";
import { Card } from "../components/Main/Card";
import { Footer } from "../components/Navigation/Footer";
import { Header } from "../components/Navigation/Header";

const Home: NextPage = () => {
  return (
    <div className="bg-white text-black">
      <Head>
        <title>Pixels QrCode</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="px-4 md:px-20">
        <Header />
        <Card />
        <Footer />
      </main>
    </div>
  );
};

export default Home;
