import Head from "next/head";
import { Footer } from "./Navigation/Footer";
import { Header } from "./Navigation/Header";
import ListButton from "./Navigation/ListButton";

const Layout = (props: any) => {
  return (
    <div className="bg-white text-black">
      <Head>
        <title>Pixels QrCode</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-4 md:px-20">
        <Header />
        <div className="w-full flex-wrap md:flex justify-right bg-green-100 rounded-lg p-5 md:p-10 my-12">
          <div className="basis-full">
            <ListButton />
          </div>
          {props.children}
        </div>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
        <Footer />
      </main>
    </div>
  );
};

export default Layout;
